### ISSUE TITLE
Vulnerability in "merge" package

### ISSUE THREAD

**Issue by alextargov** [kyma-incubator/documentation-component#89]
**Description**
There is a [PR](https://github.com/kyma-incubator/documentation-component/pull/88) from some time ago regarding the package "merge". However, whitesource has been showing high vulnerability errors (CVE-2020-28499) in [Compass Console](https://github.com/kyma-incubator/compass-console) for quite some time. If the PR is fine, can you merge it so we get rid of the error?
Thanks

**Steps to exploit**

**Risk assessment**

[{CVSS Vector String}]({CVSS Calculator URL}) **{CVSS Base Score} ({CVSS Base Severity})**

**Proposed mitigation**
Merge the [PR](https://github.com/kyma-incubator/documentation-component/pull/88)

**Comment by piotrkpc** [comment]
@alextargov  please assign labels to simplify triage.

**Comment by krasish** [comment]
@piotrkpc This issue has been open for almost 2 months now and the bot closed the [PR](https://github.com/kyma-incubator/documentation-component/pull/88) yesterday. Is there anything that stops you from not merging this PR, having in mind that this is a high vulnerability? I cannot see any reasoning on the PR. 

P.S. I reopened the PR because I believe that the version of 'merge' should be increased.
